"use client"

import { useEffect,useMemo,useState } from "react"
import { CalendarDays,ChevronLeft,ChevronRight,Loader2 } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { usePreferences } from "@/components/providers/preferences-provider"
type Task={id:string;title:string;category:string|null;priority:"low"|"medium"|"high";status:"todo"|"in_progress"|"completed";scheduled_at:string|null}
const supabase=createClient();const locale={en:"en-US",fr:"fr-FR",ar:"ar-MA"} as const
const tx={en:{title:"Monthly",intro:"Your real scheduled tasks for this month.",today:"Today",scheduled:"Scheduled",completed:"Completed",pending:"Pending",selected:"Selected day",empty:"No scheduled tasks for this day.",loading:"Loading month..."},fr:{title:"Mensuel",intro:"Vos vraies tâches planifiées pour ce mois.",today:"Aujourd'hui",scheduled:"Planifiées",completed:"Terminées",pending:"En attente",selected:"Jour sélectionné",empty:"Aucune tâche planifiée pour ce jour.",loading:"Chargement du mois..."},ar:{title:"الشهري",intro:"مهامك الحقيقية المجدولة لهذا الشهر.",today:"اليوم",scheduled:"المجدولة",completed:"المكتملة",pending:"المتبقية",selected:"اليوم المحدد",empty:"لا توجد مهام مجدولة لهذا اليوم.",loading:"جاري تحميل الشهر..."}} as const
export default function MonthlyPage(){const{language}=usePreferences();const t=tx[language];const[month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});const[selected,setSelected]=useState(new Date());const[tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
useEffect(()=>{async function load(){setLoading(true);const end=new Date(month.getFullYear(),month.getMonth()+1,1);const{data,error}=await supabase.from("tasks").select("id,title,category,priority,status,scheduled_at").gte("scheduled_at",month.toISOString()).lt("scheduled_at",end.toISOString()).order("scheduled_at",{ascending:true});if(error)setError(error.message);else setTasks((data??[])as Task[]);setLoading(false)}void load()},[month])
const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),prev=new Date(month.getFullYear(),month.getMonth(),0).getDate();return Array.from({length:42},(_,i)=>{const o=i-first.getDay()+1;if(o<1)return{day:prev+o,current:false,date:new Date(month.getFullYear(),month.getMonth()-1,prev+o)};if(o>count)return{day:o-count,current:false,date:new Date(month.getFullYear(),month.getMonth()+1,o-count)};return{day:o,current:true,date:new Date(month.getFullYear(),month.getMonth(),o)}})},[month])
const byDay=(d:Date)=>tasks.filter(x=>x.scheduled_at&&new Date(x.scheduled_at).toDateString()===d.toDateString());const selectedTasks=byDay(selected);const completed=tasks.filter(x=>x.status==="completed").length
function move(n:number){const d=new Date(month.getFullYear(),month.getMonth()+n,1);setMonth(d);setSelected(d)}function today(){const d=new Date();setMonth(new Date(d.getFullYear(),d.getMonth(),1));setSelected(d)}
return <div className="min-h-screen bg-[#F9F9FD] px-8 py-8 lg:px-10"><div className="mx-auto max-w-[1600px]"><section className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.15em] text-[#4143D5]">{t.title}</p><h1 className="mt-2 text-[32px] font-semibold text-neutral-950">{month.toLocaleDateString(locale[language],{month:"long",year:"numeric"})}</h1><p className="mt-1 text-sm text-neutral-500">{t.intro}</p></div><div className="flex h-10 items-center rounded-xl border border-neutral-200 bg-white p-1"><button onClick={()=>move(-1)} className="h-8 w-8"><ChevronLeft className="mx-auto h-4 w-4"/></button><button onClick={today} className="h-8 rounded-lg bg-neutral-100 px-4 text-xs font-semibold">{t.today}</button><button onClick={()=>move(1)} className="h-8 w-8"><ChevronRight className="mx-auto h-4 w-4"/></button></div></section><section className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label={t.scheduled} value={tasks.length}/><Stat label={t.completed} value={completed}/><Stat label={t.pending} value={tasks.length-completed}/></section>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
<section className="mt-6 grid gap-6 xl:grid-cols-12"><div className="overflow-hidden rounded-2xl border border-neutral-200 bg-white xl:col-span-9">{loading?<div className="flex min-h-[560px] items-center justify-center text-neutral-400"><Loader2 className="me-2 h-5 w-5 animate-spin"/>{t.loading}</div>:<><div className="grid grid-cols-7 bg-neutral-50 py-3 text-center text-[10px] font-semibold uppercase text-neutral-500">{Array.from({length:7},(_,i)=>new Date(2026,0,4+i).toLocaleDateString(locale[language],{weekday:"short"})).map(x=><div key={x}>{x}</div>)}</div><div className="grid grid-cols-7 gap-px bg-neutral-200">{cells.map((c,i)=>{const list=c.current?byDay(c.date):[];const active=c.date.toDateString()===selected.toDateString();return <button key={i} onClick={()=>c.current&&setSelected(c.date)} className={`min-h-[118px] bg-white p-2 text-start ${active?"bg-[#EEEEFF]":""} ${c.current?"":"opacity-35"}`}><span className="text-xs font-semibold">{c.day}</span><div className="mt-2 space-y-1">{list.slice(0,3).map(x=><div key={x.id} className={`truncate rounded-md px-1.5 py-1 text-[9px] font-semibold ${x.status==="completed"?"bg-emerald-50 text-emerald-700 line-through":"bg-[#EEEEFF] text-[#4143D5]"}`}>{x.title}</div>)}</div></button>})}</div></>}</div><aside className="xl:col-span-3"><div className="rounded-2xl border border-neutral-200 bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[#4143D5]">{t.selected}</p><h2 className="mt-1 text-lg font-semibold">{selected.toLocaleDateString(locale[language],{weekday:"long",month:"long",day:"numeric"})}</h2><div className="mt-5 space-y-3">{selectedTasks.length===0?<div className="rounded-xl bg-neutral-50 px-4 py-8 text-center"><CalendarDays className="mx-auto h-5 w-5 text-neutral-300"/><p className="mt-2 text-xs text-neutral-400">{t.empty}</p></div>:selectedTasks.map(x=><div key={x.id} className="rounded-xl bg-neutral-50 p-3"><p className="text-[10px] font-semibold text-[#4143D5]">{new Date(x.scheduled_at!).toLocaleTimeString(locale[language],{hour:"2-digit",minute:"2-digit"})}</p><p className="mt-2 text-sm font-semibold">{x.title}</p>{x.category&&<p className="mt-1 text-[10px] text-neutral-400">{x.category}</p>}</div>)}</div></div></aside></section></div></div>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-neutral-200 bg-white p-5"><p className="text-xs text-neutral-400">{label}</p><p className="mt-2 text-2xl font-bold text-neutral-950">{value}</p></div>}
