"use client"

import { useEffect,useMemo,useState } from "react"
import { CheckCircle2,Clock3,Loader2,Target,TrendingUp } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { usePreferences } from "@/components/providers/preferences-provider"
type Task={id:string;status:"todo"|"in_progress"|"completed";created_at:string;completed_at:string|null;duration_minutes:number|null;category:string|null}
type Goal={id:string;status:"active"|"completed"|"paused"|"archived";current_value:number;target_value:number|null}
const supabase=createClient();const tx={en:{title:"Analytics",intro:"Live productivity metrics calculated from your Taskora data.",tasks:"Tasks",completed:"Completed",rate:"Completion rate",focus:"Planned focus time",goals:"Goals",goalsDone:"Goals completed",status:"Task status",categories:"Task categories",empty:"No data yet. Create tasks and goals to build your analytics.",loading:"Loading analytics...",todo:"Todo",inProgress:"In progress"},fr:{title:"Analyses",intro:"Indicateurs de productivité calculés à partir de vos données Taskora.",tasks:"Tâches",completed:"Terminées",rate:"Taux de complétion",focus:"Temps de focus planifié",goals:"Objectifs",goalsDone:"Objectifs terminés",status:"Statut des tâches",categories:"Catégories des tâches",empty:"Aucune donnée. Créez des tâches et objectifs pour alimenter vos analyses.",loading:"Chargement des analyses...",todo:"À faire",inProgress:"En cours"},ar:{title:"التحليلات",intro:"مؤشرات إنتاجية محسوبة من بيانات Taskora الحقيقية.",tasks:"المهام",completed:"المكتملة",rate:"نسبة الإنجاز",focus:"وقت التركيز المخطط",goals:"الأهداف",goalsDone:"الأهداف المكتملة",status:"حالة المهام",categories:"فئات المهام",empty:"لا توجد بيانات بعد. أنشئ مهاما وأهدافا لعرض التحليلات.",loading:"جاري تحميل التحليلات...",todo:"للإنجاز",inProgress:"قيد التنفيذ"}} as const
export default function AnalyticsPage(){const{language}=usePreferences();const t=tx[language];const[tasks,setTasks]=useState<Task[]>([]);const[goals,setGoals]=useState<Goal[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
useEffect(()=>{async function load(){setLoading(true);const[a,b]=await Promise.all([supabase.from("tasks").select("id,status,created_at,completed_at,duration_minutes,category"),supabase.from("goals").select("id,status,current_value,target_value").neq("status","archived")]);if(a.error||b.error)setError(a.error?.message??b.error?.message??"Error");else{setTasks((a.data??[])as Task[]);setGoals((b.data??[])as Goal[])}setLoading(false)}void load()},[])
const completed=tasks.filter(x=>x.status==="completed").length,rate=tasks.length?Math.round(completed/tasks.length*100):0,minutes=tasks.reduce((s,x)=>s+(x.duration_minutes??0),0),goalsDone=goals.filter(x=>x.status==="completed").length
const cats=useMemo(()=>{const m=new Map<string,number>();tasks.forEach(x=>{const k=x.category?.trim()||"—";m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1])},[tasks])
if(loading)return <div className="flex min-h-[70vh] items-center justify-center text-neutral-400"><Loader2 className="me-2 h-5 w-5 animate-spin"/>{t.loading}</div>
return <div className="min-h-screen bg-[#F9F9FD] px-8 py-8 lg:px-10"><div className="mx-auto max-w-[1400px]"><p className="text-[11px] font-semibold uppercase tracking-[.15em] text-[#4143D5]">{t.title}</p><h1 className="mt-2 text-[32px] font-semibold text-neutral-950">{t.title}</h1><p className="mt-1 text-sm text-neutral-500">{t.intro}</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
<section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={<Target/>} label={t.tasks} value={tasks.length}/><Kpi icon={<CheckCircle2/>} label={t.completed} value={completed}/><Kpi icon={<TrendingUp/>} label={t.rate} value={rate+"%"}/><Kpi icon={<Clock3/>} label={t.focus} value={Math.round(minutes/60*10)/10+"h"}/></section>
{tasks.length===0&&goals.length===0?<div className="mt-6 rounded-2xl border border-dashed border-neutral-200 bg-white p-16 text-center text-sm text-neutral-400">{t.empty}</div>:<section className="mt-6 grid gap-6 lg:grid-cols-3"><article className="rounded-2xl border border-neutral-200 bg-white p-6"><h2 className="font-semibold">{t.status}</h2><Bars rows={[[t.completed,completed],[t.todo,tasks.filter(x=>x.status==="todo").length],[t.inProgress,tasks.filter(x=>x.status==="in_progress").length]]} total={tasks.length}/></article><article className="rounded-2xl border border-neutral-200 bg-white p-6"><h2 className="font-semibold">{t.goals}</h2><div className="mt-6 text-4xl font-bold text-[#4143D5]">{goalsDone}/{goals.length}</div><p className="mt-2 text-xs text-neutral-400">{t.goalsDone}</p></article><article className="rounded-2xl border border-neutral-200 bg-white p-6"><h2 className="font-semibold">{t.categories}</h2><Bars rows={cats.slice(0,6)} total={tasks.length}/></article></section>}</div></div>}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-2xl border border-neutral-200 bg-white p-5"><div className="flex items-center justify-between text-xs text-neutral-400"><span>{label}</span><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span></div><p className="mt-4 text-3xl font-bold text-neutral-950">{value}</p></div>}
function Bars({rows,total}:{rows:[string,number][];total:number}){return <div className="mt-5 space-y-4">{rows.map(([label,value])=><div key={label}><div className="flex justify-between text-xs"><span>{label}</span><span>{value}</span></div><div className="mt-2 h-2 rounded-full bg-neutral-100"><div className="h-full rounded-full bg-[#4143D5]" style={{width:(total?value/total*100:0)+"%"}}/></div></div>)}</div>}
