"use client"
import Link from "next/link"
import { useEffect,useState } from "react"
import { Crown,Download,FileSpreadsheet,Loader2 } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { usePreferences } from "@/components/providers/preferences-provider"
const supabase=createClient()
const tx={en:{title:"Reports & Export",intro:"Export your real Taskora data for reporting and analysis.",locked:"Reports and exports are a Pro feature.",upgrade:"Upgrade to Pro",csv:"Export tasks CSV",goals:"Export goals CSV"},fr:{title:"Rapports & Export",intro:"Exportez vos données Taskora pour vos rapports et analyses.",locked:"Les rapports et exports sont une fonction Pro.",upgrade:"Passer à Pro",csv:"Exporter les tâches CSV",goals:"Exporter les objectifs CSV"},ar:{title:"التقارير والتصدير",intro:"صدّر بيانات Taskora للتقارير والتحليل.",locked:"التقارير والتصدير ميزة Pro.",upgrade:"الترقية إلى Pro",csv:"تصدير المهام CSV",goals:"تصدير الأهداف CSV"}} as const
export default function ReportsPage(){const{language}=usePreferences();const t=tx[language];const[plan,setPlan]=useState<"free"|"pro">("free"),[loading,setLoading]=useState(true)
useEffect(()=>{void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(user){const{data}=await supabase.from("profiles").select("plan").eq("user_id",user.id).maybeSingle();setPlan(data?.plan==="pro"?"pro":"free")}setLoading(false)})()},[])
async function exportTable(table:"tasks"|"goals"){const{data,error}=await supabase.from(table).select("*");if(error||!data)return;const rows=data as Record<string,unknown>[];if(!rows.length)return;const keys=Object.keys(rows[0]);const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[keys.join(","),...rows.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`taskora-${table}.csv`;a.click();URL.revokeObjectURL(a.href)}
if(loading)return <div className="flex min-h-[70vh] items-center justify-center"><Loader2 className="h-5 w-5 animate-spin"/></div>
if(plan!=="pro")return <main className="min-h-screen bg-[#F9F9FD] p-10 dark:bg-[#111318]"><div className="mx-auto max-w-3xl rounded-3xl border bg-white p-10 text-center dark:border-neutral-800 dark:bg-[#1C1F26]"><Crown className="mx-auto h-10 w-10 text-[#4143D5]"/><h1 className="mt-5 text-3xl font-semibold dark:text-white">{t.locked}</h1><Link href="/dashboard/upgrade" className="mt-6 inline-flex rounded-lg bg-[#4143D5] px-5 py-3 text-sm font-semibold text-white">{t.upgrade}</Link></div></main>
return <main className="min-h-screen bg-[#F9F9FD] p-8 dark:bg-[#111318] dark:text-white"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-semibold">{t.title}</h1><p className="mt-2 text-sm text-neutral-500">{t.intro}</p><div className="mt-7 grid gap-4 md:grid-cols-2"><ExportCard icon={<FileSpreadsheet/>} title={t.csv} onClick={()=>void exportTable("tasks")}/><ExportCard icon={<Download/>} title={t.goals} onClick={()=>void exportTable("goals")}/></div></div></main>}
function ExportCard({icon,title,onClick}:{icon:React.ReactNode;title:string;onClick:()=>void}){return <button onClick={onClick} className="flex items-center gap-4 rounded-2xl border border-neutral-200 bg-white p-6 text-left transition hover:border-[#4143D5] dark:border-neutral-800 dark:bg-[#1C1F26]"><span className="text-[#4143D5] [&>svg]:h-6 [&>svg]:w-6">{icon}</span><span className="font-semibold">{title}</span></button>}
