"use client"

import Link from "next/link"
import { useEffect, useMemo, useState } from "react"
import { Crown, Loader2, Pause, Play, RotateCcw, TimerReset } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { usePreferences } from "@/components/providers/preferences-provider"

const supabase=createClient()
const tx={
 en:{title:"Focus",intro:"Run distraction-free focus sessions and keep a real history of your work.",pro:"Pro feature",upgrade:"Upgrade to Pro",start:"Start focus",pause:"Pause",resume:"Resume",reset:"Reset",complete:"Complete session",today:"Today",sessions:"Sessions",minutes:"Focus minutes",history:"Recent sessions",empty:"No focus sessions yet.",locked:"Focus sessions are available on Taskora Pro.",lockedText:"Upgrade to unlock the focus timer, session history and focus analytics.",task:"Focus task",noTask:"No linked task",saveFailed:"Could not save this focus session. Please try again."},
 fr:{title:"Focus",intro:"Lancez des sessions de concentration et conservez un historique réel de votre travail.",pro:"Fonction Pro",upgrade:"Passer à Pro",start:"Démarrer",pause:"Pause",resume:"Reprendre",reset:"Réinitialiser",complete:"Terminer la session",today:"Aujourd’hui",sessions:"Sessions",minutes:"Minutes de focus",history:"Sessions récentes",empty:"Aucune session de focus.",locked:"Les sessions de focus sont disponibles avec Taskora Pro.",lockedText:"Passez à Pro pour débloquer le minuteur, l’historique et les analyses de focus.",task:"Tâche de focus",noTask:"Aucune tâche liée",saveFailed:"Impossible d’enregistrer cette session de focus. Réessayez."},
 ar:{title:"التركيز",intro:"ابدأ جلسات تركيز بدون تشتيت واحتفظ بسجل حقيقي لعملك.",pro:"ميزة Pro",upgrade:"الترقية إلى Pro",start:"ابدأ التركيز",pause:"إيقاف مؤقت",resume:"متابعة",reset:"إعادة الضبط",complete:"إنهاء الجلسة",today:"اليوم",sessions:"الجلسات",minutes:"دقائق التركيز",history:"الجلسات الأخيرة",empty:"لا توجد جلسات تركيز بعد.",locked:"جلسات التركيز متاحة في Taskora Pro.",lockedText:"قم بالترقية لفتح المؤقت وسجل الجلسات وتحليلات التركيز.",task:"مهمة التركيز",noTask:"بدون مهمة مرتبطة",saveFailed:"تعذر حفظ جلسة التركيز. حاول مرة أخرى."}
} as const
type Session={id:string;duration_minutes:number;started_at:string;completed_at:string|null;task_id:string|null;tasks:{title:string}[]|null}
type FocusTask={id:string;title:string}

export default function FocusPage(){
 const{language}=usePreferences();const t=tx[language];const locale=language==="fr"?"fr-FR":language==="ar"?"ar-MA":"en-US"
 const[plan,setPlan]=useState<"free"|"pro">("free"),[loading,setLoading]=useState(true),[sessions,setSessions]=useState<Session[]>([]),[tasks,setTasks]=useState<FocusTask[]>([]),[taskId,setTaskId]=useState("")
 const[seconds,setSeconds]=useState(25*60),[running,setRunning]=useState(false),[startedAt,setStartedAt]=useState<string|null>(null),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState<string|null>(null)
 useEffect(()=>{async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const[p,s,k]=await Promise.all([supabase.from("profiles").select("plan").eq("user_id",user.id).maybeSingle(),supabase.from("focus_sessions").select("id,duration_minutes,started_at,completed_at,task_id,tasks(title)").order("started_at",{ascending:false}).limit(10),supabase.from("tasks").select("id,title").neq("status","completed").order("created_at",{ascending:false}).limit(100)]);setPlan(p.data?.plan==="pro"?"pro":"free");setSessions((s.data??[])as unknown as Session[]);setTasks((k.data??[])as FocusTask[]);setLoading(false)}void load()},[])
 useEffect(()=>{if(!running)return;const id=window.setInterval(()=>setSeconds(v=>{if(v<=1){setRunning(false);return 0}return v-1}),1000);return()=>window.clearInterval(id)},[running])
 useEffect(()=>{if(seconds===0&&startedAt&&!saving&&!saveError)void complete()},[seconds,startedAt,saving,saveError])
 const today=useMemo(()=>{const d=new Date().toDateString();return sessions.filter(s=>new Date(s.started_at).toDateString()===d)},[sessions])
 async function complete(){if(!startedAt)return;setSaveError(null);setSaving(true);const elapsed=Math.max(1,Math.round((25*60-seconds)/60));const{data:{user}}=await supabase.auth.getUser();if(!user){setSaveError(t.saveFailed);setRunning(false);setSaving(false);return}const{data,error}=await supabase.from("focus_sessions").insert({user_id:user.id,task_id:taskId||null,duration_minutes:elapsed,started_at:startedAt,completed_at:new Date().toISOString()}).select("id,duration_minutes,started_at,completed_at,task_id,tasks(title)").single();if(error||!data){setSaveError(t.saveFailed);setRunning(false);setSaving(false);return}setSessions(v=>[data as unknown as Session,...v]);setRunning(false);setStartedAt(null);setTaskId("");setSeconds(25*60);setSaving(false)}
 if(loading)return <div className="flex min-h-[70vh] items-center justify-center text-neutral-400"><Loader2 className="me-2 h-5 w-5 animate-spin"/></div>
 if(plan!=="pro")return <main className="min-h-screen bg-[#F9F9FD] px-8 py-10 dark:bg-[#111318]"><div className="mx-auto max-w-3xl rounded-3xl border border-[#4143D5]/20 bg-white p-10 text-center dark:bg-[#1C1F26]"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#EEEEFF] text-[#4143D5]"><Crown/></div><span className="mt-5 inline-block rounded-full bg-[#EEEEFF] px-3 py-1 text-[10px] font-bold uppercase text-[#4143D5]">{t.pro}</span><h1 className="mt-4 text-3xl font-semibold dark:text-white">{t.locked}</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-neutral-500">{t.lockedText}</p><Link href="/dashboard/upgrade" className="mt-7 inline-flex h-11 items-center rounded-lg bg-[#4143D5] px-5 text-sm font-semibold text-white">{t.upgrade}</Link></div></main>
 const mm=String(Math.floor(seconds/60)).padStart(2,"0"),ss=String(seconds%60).padStart(2,"0")
 return <main className="min-h-screen bg-[#F9F9FD] px-8 py-8 dark:bg-[#111318] dark:text-white"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-widest text-[#4143D5]">{t.pro}</p><h1 className="mt-2 text-3xl font-semibold">{t.title}</h1><p className="mt-1 text-sm text-neutral-500">{t.intro}</p><div className="mt-7 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><section className="rounded-3xl border border-neutral-200 bg-white p-8 text-center dark:border-neutral-800 dark:bg-[#1C1F26]"><TimerReset className="mx-auto h-7 w-7 text-[#4143D5]"/><label className="mx-auto mt-6 block max-w-sm text-left text-xs font-semibold text-neutral-500">{t.task}<select value={taskId} disabled={!!startedAt} onChange={e=>setTaskId(e.target.value)} className="mt-2 h-10 w-full rounded-lg border border-neutral-200 bg-neutral-50 px-3 text-sm outline-none dark:border-neutral-700 dark:bg-[#252830]"><option value="">{t.noTask}</option>{tasks.map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select></label><div className="my-8 text-7xl font-semibold tabular-nums">{mm}:{ss}</div><div className="flex flex-wrap justify-center gap-2">{!startedAt?<button onClick={()=>{setSaveError(null);setStartedAt(new Date().toISOString());setRunning(true)}} className="rounded-lg bg-[#4143D5] px-5 py-2.5 text-sm font-semibold text-white"><Play className="me-2 inline h-4 w-4"/>{t.start}</button>:<><button onClick={()=>setRunning(v=>!v)} className="rounded-lg bg-[#4143D5] px-5 py-2.5 text-sm font-semibold text-white">{running?<Pause className="me-2 inline h-4 w-4"/>:<Play className="me-2 inline h-4 w-4"/>}{running?t.pause:t.resume}</button><button onClick={()=>{setSaveError(null);setRunning(false);setStartedAt(null);setTaskId("");setSeconds(1500)}} className="rounded-lg border px-4 py-2.5 text-sm"><RotateCcw className="me-2 inline h-4 w-4"/>{t.reset}</button><button disabled={saving} onClick={complete} className="rounded-lg border px-4 py-2.5 text-sm">{t.complete}</button></>}</div>{saveError&&<p className="mt-4 text-sm font-medium text-red-600">{saveError}</p>}</section><section className="space-y-4"><Stat label={t.sessions} value={today.length}/><Stat label={t.minutes} value={today.reduce((a,b)=>a+b.duration_minutes,0)}/></section></div><section className="mt-5 rounded-2xl border border-neutral-200 bg-white p-6 dark:border-neutral-800 dark:bg-[#1C1F26]"><h2 className="font-semibold">{t.history}</h2>{sessions.length===0?<p className="mt-5 text-sm text-neutral-400">{t.empty}</p>:<div className="mt-4 divide-y dark:divide-neutral-800">{sessions.map(s=><div key={s.id} className="flex justify-between py-3 text-sm"><span><span>{new Date(s.started_at).toLocaleString(locale)}</span>{s.tasks?.[0]?.title&&<span className="mt-1 block text-xs text-neutral-400">{s.tasks[0].title}</span>}</span><strong>{s.duration_minutes} min</strong></div>)}</div>}</section></div></main>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-neutral-200 bg-white p-6 dark:border-neutral-800 dark:bg-[#1C1F26]"><p className="text-xs text-neutral-400">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>}
